name: my_preloved
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  envied: ^0.3.0
  envied_generator: ^0.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.20.0
  flutter_riverpod: ^2.3.1
  flutter_screenutil: ^5.7.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  go_router: ^7.0.1
  google_fonts: ^5.1.0
  json_annotation: ^4.7.0
  logger: ^2.0.1
  riverpod_annotation: ^2.0.1
  supabase_flutter: ^1.10.16
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: any
  riverpod_generator: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
